FROM tomcat

WORKDIR /app

#ADD . /app
#RUN rm /etc/apt/sources.list
#RUN cp /app/sources.list /etc/apt
#RUN apt-get update && apt-get install apache2

# Make port 80 available to the world outside this container
EXPOSE 8080
#/usr/local/tomcat/webapps/ROOT
CMD ["startup.sh"]